/**
 * The single icon source for the whole product.
 *
 * We use Phosphor Icons (a large, cohesive, more refined set than the previous
 * generic icons) but keep the names the app already uses by aliasing here — so
 * swapping the icon library was a one-file change, and swapping it again later
 * is too. Import icons from "@/components/ui/icons", never from a vendor
 * package directly.
 */
// Type-only (erased at runtime, so no RSC-unsafe barrel is loaded); the
// runtime components come from the SSR-safe entrypoint below.
export type { Icon as IconType } from "@phosphor-icons/react"

export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Archive,
  ArrowCounterClockwise as ArchiveRestore,
  ArrowLeft,
  ArrowsLeftRight as ArrowLeftRight,
  ArrowRight,
  ChartBar as BarChart3,
  Bell,
  BellSlash as BellOff,
  BookOpen,
  Brain,
  Buildings as Building2,
  Calendar,
  CalendarCheck,
  CalendarDots as CalendarDays,
  Checks as CheckCheck,
  CheckCircle,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  Clock,
  AddressBook as Contact,
  CurrencyDollar as DollarSign,
  DownloadSimple as Download,
  ArrowSquareOut as ExternalLink,
  Eye,
  FileText as FileCheck,
  FileText,
  Handshake,
  Hash,
  ImageSquare as ImagePlus,
  Key as KeyRound,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  Lightbulb,
  LinkSimple as Link2,
  ListChecks as ListTodo,
  CircleNotch as Loader2,
  SignOut as LogOut,
  Envelope as Mail,
  MapPin,
  Megaphone,
  ChatCircle as MessageCircle,
  ChatText as MessageSquare,
  Monitor,
  Moon,
  Newspaper,
  NotePencil as PenSquare,
  Plus,
  ArrowClockwise as RotateCw,
  Scroll as ScrollText,
  MagnifyingGlass as Search,
  Gear as Settings,
  ShieldCheck,
  Sparkle as Sparkles,
  Storefront as Store,
  Sun,
  Timer,
  Trash as Trash2,
  UploadSimple as Upload,
  UserGear as UserCog,
  UserPlus,
  User as UserRound,
  Users,
  X,
  Paperclip,
  ChatCircleDots,
  CaretDoubleLeft,
  CaretDoubleRight,
  DotsThree,
  FunnelSimple,
  SlidersHorizontal,
} from "@phosphor-icons/react/ssr"
